name: subtrack_prototype
description: A subscription tracking application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase Core
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  # State Management
  provider: ^6.1.2
  # Utilities
  intl: ^0.19.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true